### ISSUE TITLE
Map file parse error when trying to load TS Looping Waves ini

### ISSUE THREAD

**Issue by MikillRosen** [whensonZWS/Trigger-Analyzer#3]
INI and map version: [Looping Waves.zip](https://github.com/whensonZWS/Trigger-Analyzer/files/6254874/Looping.Waves.zip)

**Comment by whensonZWS** [comment]
Map problem: Tag MAWV3204 is pointing to a non-existent trigger declaration, MAWV3203, yet it has corresponding events and triggers.
The tool assumes a one to one mapping between Tags and Trigger. The next commit will fix this issue by ignoring non-existent triggers and produce a warning text in the info box.
